version: '3.9'

services:
  postgres:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
    ports:
      - '9200:9200'
    labels:
      org.springframework.boot.ignore: true
    healthcheck:
      interval: 5s
      retries: 10
      test: curl --write-out 'HTTP %{http_code}' -u elastic:elastic --fail --silent --output /dev/null http://localhost:9200/_cat/health