spring:
  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: false
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
  application:
    name: eSafe (Prod)
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    show-sql: false
    open-in-view: false
  sql:
    init:
      mode: always
  liquibase:
    drop-first: false
    contexts: prod

jdbc:
  datasource-proxy:
    query:
      logger-name: fr.xelians.esafe.jpa.query
    include-parameter-values: true
# Actuator config
# We keep readiness and liveness checks on the server servlet.
# Management servlet can continue to answer whereas server's one don't.
management:
  endpoint:
    health:
      group:
        readiness:
          include: db
          additional-path: "server:/readyz"
        liveness:
          additional-path: "server:/livez"
      probes:
        enabled: true
        add-additional-paths: true
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    baggage:
      correlation:
        fields: x-application-id, x-tenant-id
      remote-fields: x-application-id, x-tenant-id
    sampling:
      probability: 1
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  info:
    git:
      mode: full

## Properties specific to app (functional properties)
app:
  version: '@project.version@'
  # Processing properties
  processing:
    threads: 0
  # Indexing properties
  indexing:
    threads: 16
    on-start:
      reset: false
      create-if-missing: true
  # Tenant encryption (seconds)
  tenant:
    encryption:
      secret: Voici un petit mot de passe composé de @10453265 caractères !! Il est donc super solide car de plus j'ai ajouté des caractères spéciaux comme des $ & des \#. J'adore!
      salt: 56, 16, -15, 89, 65, -106, -17, 77
      expiration: 0
  # Dip export properties (byte)
  dipexport:
    maxSize: 1_000_000_000
  # Storage properties
  storage:
    offer:
      # File system Offers
      fs:
        - capacity: SMALL
          name: FS01
          node: node1
          root: fs01
        - capacity: MEDIUM
          name: FS02
          node: node2
          root: fs02
      # S3 Offers
      s3:
        - accessKeyId: hvA0vo3Nu8yruvQ3_
          concurrency: 32
          endpoint: http://192.168.1.82:9000
          provider: MINIO
          name: minio01
          region: US_EAST_1
          secretAccessKey: VYo8QiN40bd4PKyC
  batch:
    backup:
      operation:
        fixedDelay: 300000
        initialDelay: 300000
    clean:
      cron: 0 0 3 * * ?
      running: 48   # Delay in hours before updating operations with init and run status to error
      succeeded: 48 # Delay in hours before deleting successful operations from database
      failed: 168   # Delay in hours before deleting failed operations from database
    retry:
      fixedDelay: 900000
      initialDelay: 1000
    secure:
      fixedDelay: PT3600S
      initialDelay: PT60S
    cluster:
      fixedDelay: 120000 # 120 seconds
      initialDelay: 0
    store:
      operation:
        fixedDelay: 2000
        initialDelay: 1000
  logging:
    request:
      path-to-ignore: /actuator,/v3/api-docs,/swagger-ui,/readyz,/livez

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

